# Generated by Django 3.0.4 on 2020-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.IntegerField()),
                ('picture', models.CharField(max_length=300)),
                ('asset', models.IntegerField()),
            ],
        ),
    ]
